name: powershell

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: .\MyScripts\date.ps1
      shell: powershell

